// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhi3CuQ0jYPv9BnrXCht7exyK92rZOi4',
    appId: '1:733107092871:web:7fd138868459e42f69a722',
    messagingSenderId: '733107092871',
    projectId: 'flutter-firebase-app-27402',
    authDomain: 'flutter-firebase-app-27402.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-27402.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUOsKGXaX-9NVr270E3xjsZwsMRdaUHMk',
    appId: '1:733107092871:android:853adca269e6444069a722',
    messagingSenderId: '733107092871',
    projectId: 'flutter-firebase-app-27402',
    storageBucket: 'flutter-firebase-app-27402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJgghmxQh3arV-fY7j0SvI4ACBDw6foQ',
    appId: '1:733107092871:ios:ab0af54664ddda8569a722',
    messagingSenderId: '733107092871',
    projectId: 'flutter-firebase-app-27402',
    storageBucket: 'flutter-firebase-app-27402.firebasestorage.app',
    iosBundleId: 'br.com.enzolduarte.flutterPasswordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJgghmxQh3arV-fY7j0SvI4ACBDw6foQ',
    appId: '1:733107092871:ios:ab0af54664ddda8569a722',
    messagingSenderId: '733107092871',
    projectId: 'flutter-firebase-app-27402',
    storageBucket: 'flutter-firebase-app-27402.firebasestorage.app',
    iosBundleId: 'br.com.enzolduarte.flutterPasswordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJhi3CuQ0jYPv9BnrXCht7exyK92rZOi4',
    appId: '1:733107092871:web:d2ae00d0f848be0769a722',
    messagingSenderId: '733107092871',
    projectId: 'flutter-firebase-app-27402',
    authDomain: 'flutter-firebase-app-27402.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-27402.firebasestorage.app',
  );
}
